
server:
  port: 8000 
eureka: 
  client:
    service-url: 
      defaultZone:  http://localhost:8761/eureka
spring:
  application:
    name: cambioservice
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5431/cambio_service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5431/cambio_service
    user: postgres
    password: password

springdoc:
  api-docs:
    path: cambioservice/v3/api-docs