version: '3.9'

services:
  
  namingserver:
    image: joaopaulocunhafaria/namingserver:latest
    ports:
      - 8761:8761
    networks:
      - joao-network

  api-gateway:
    image: joaopaulocunhafaria/api-gateway:latest
    ports:
      - 8765:8765
    depends_on: 
      - namingserver
    environment:
       SPRING.ZIPKIN.BASEURL:  http://zipkin:9411/
       EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://namingserver:8761/eureka
    networks:
      - joao-network 
     
  cambio-service:
    image: joaopaulocunhafaria/cambioservice:latest
    ports:
      - 8000:8000
    depends_on: 
      - namingserver
      - cambio-db
    environment:
       SPRING.ZIPKIN.BASEURL:  http://zipkin:9411/
       EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://namingserver:8761/eureka
       SPRING.DATASOURCE.URL: jdbc:postgresql://cambio-db:5432/cambio_service 
       SPRING.FLYWAY.URL: jdbc:postgresql://cambio-db:5432/cambio_service 
       SPRING.DATASOURCE.USERNAME: postgres 
       SPRING.DATASOURCE.PASSWORD: password
       SPRING.FLYWAY.USER: postgres 
       SPRING.FLYWAY.PASSWORD: password
       
    networks:
      - joao-network 
  
  
  book-service:
    image: joaopaulocunhafaria/bookservice:latest
    ports:
      - 8100:8100
    depends_on: 
      - namingserver
      - book-db
    environment:
       SPRING.ZIPKIN.BASEURL:  http://zipkin:9411/
       EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://namingserver:8761/eureka
       SPRING.DATASOURCE.URL: jdbc:postgresql://book-db:5432/book_service 
       SPRING.FLYWAY.URL: jdbc:postgresql://book-db:5432/book_service 
       SPRING.DATASOURCE.USERNAME: postgres 
       SPRING.DATASOURCE.PASSWORD: password
       SPRING.FLYWAY.USER: postgres 
       SPRING.FLYWAY.PASSWORD: password 
    networks:
      - joao-network 

 
  cambio-db:
    image: postgres:17.0-bookworm
    ports:
      - "5431:5432"
    restart: always
    shm_size: 128mb  # Limite de memória compartilhada
    environment:
      POSTGRES_DB: cambio_service       
      POSTGRES_PASSWORD: password    
    networks:
      - joao-network 

  
  book-db:
    image: postgres:17.0-bookworm
    ports:
      - "5430:5432"
    restart: always
    shm_size: 128mb  # Limite de memória compartilhada
    environment:
      POSTGRES_DB: book_service      # Define o nome do usuário
      POSTGRES_PASSWORD: password    # Define a senha do root (não nativa no Postgres, mas pode ser usado para definir o usuário padrão)
    networks:
      - joao-network 

  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - joao-network  

networks:
  joao-network:
    driver: bridge
