server:
  port: 8100
eureka: 
  client:
    service-url: 
      defaultZone:  http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      foobar : 
        max-attempts: 10
      findbook: 
        max-attempts: 5
        wait-duration: 2s 

spring: 
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: bookservice
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5430/book_service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5430/book_service
    schemas: 
    - book
    user: postgres
    password: password
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
springdoc:
  api-docs:
    path: bookservice/v3/api-docs      