spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
      - id: cambioservice
        uri: lb://cambioservice
        predicates: 
        - Path=/cambioservice/**
      - id: bookservice
        uri: lb://bookservice
        predicates: 
        - Path=/bookservice/**   
      - id: openapi
        uri: lb://api-gateway
        predicates: 
        - Path=/v3/api-docs/**
        filters: 
        -   RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs 
        
server:
  port: 8765
eureka: 
  client:
    service-url: 
      defaultZone:  http://localhost:8761/eureka

