server:
  port: 8100
eureka: 
  client:
    service-url: 
      defaultZone:  http://localhost:8761/eureka
resilience4j:
 retry:
    instances:
      findbook:
        max-attempts: 5
        wait-duration: 2s 

 circuitbreaker:
    instances:
      findbook:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException

 ratelimiter:
    instances:
      findbook:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

 bulkhead:
    instances:
      findbook:
        max-concurrent-calls: 10
        max-wait-duration: 500ms 

 timelimiter:
    instances:
      findbook:
        timeout-duration: 3s

 metrics:
    enable: true

spring: 
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: bookservice
  datasource:
    driver-class-name: org.postgresql.Driver
    username: joao
    password: min3cr3ft
    url: jdbc:postgresql://localhost:5432/book_service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/book_service
    schemas: 
    - book
    user: joao
    password: min3cr3ft
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
springdoc:
  api-docs:
    path: bookservice/v3/api-docs      